# Generated by Django 3.1.6 on 2021-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210413_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delete_profile',
            field=models.BooleanField(default=False),
        ),
    ]
