# Generated by Django 3.1.7 on 2021-02-22 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fault', models.CharField(max_length=140)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField(auto_now_add=True)),
                ('booking_date', models.DateField()),
                ('approve_booking', models.BooleanField(default=False)),
                ('count_bookings', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtype')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.fault')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.phonemodel')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
