# Generated by Django 3.1.7 on 2021-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='count_bookings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
