# Generated by Django 3.1.7 on 2021-03-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refuse',
            field=models.BooleanField(default=False),
        ),
    ]
